name: SSA 2 - Workflow with Multiple Deployments, Steps, and Logs

on:
  workflow_dispatch:
    inputs:
      port_payload:
        required: true
        description: "Port's payload with details about the workflow entity."
        type: string

jobs:
  create-deployments:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Access Token
        id: generate-token
        run: |
          access_token=$(curl --location --request POST 'https://api.getport.io/v1/auth/access_token' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "clientId": "'${{ secrets.PORT_CLIENT_ID }}'",
              "clientSecret": "'${{ secrets.PORT_CLIENT_SECRET }}'"
          }' | jq '.accessToken' | sed 's/"//g')
          echo "ACCESS_TOKEN=$access_token" >> $GITHUB_ENV

      - name: Sleep for 5 Seconds
        run: sleep 5

      - name: Trigger First Deployment
        id: deploy-1
        run: |
          curl -L -X POST "https://api.getport.io/v1/blueprints/deployment/entities" \
          -H "Authorization: Bearer ${{ env.ACCESS_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "identifier": "deployment-1-${{ github.run_id }}",
            "title": "First Deployment for Workflow - ${{ fromJson(inputs.port_payload).workflow_id }}",
            "blueprint": "deployment",
            "properties": {
              "status": "IN_PROGRESS",
              "status_message": "First deployment is in progress."
            },
            "relations": {
              "workflow": "${{ fromJson(inputs.port_payload).workflow_id }}"
            }
          }'

      - name: Sleep for 5 Seconds
        run: sleep 5

      - name: Trigger Second Deployment
        id: deploy-2
        run: |
          curl -L -X POST "https://api.getport.io/v1/blueprints/deployment/entities" \
          -H "Authorization: Bearer ${{ env.ACCESS_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "identifier": "deployment-2-${{ github.run_id }}",
            "title": "Second Deployment for Workflow - ${{ fromJson(inputs.port_payload).workflow_id }}",
            "blueprint": "deployment",
            "properties": {
              "status": "IN_PROGRESS",
              "status_message": "Second deployment is in progress."
            },
            "relations": {
              "workflow": "${{ fromJson(inputs.port_payload).workflow_id }}"
            }
          }'

  process-steps:
    needs: create-deployments
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Access Token
        id: generate-token
        run: |
          access_token=$(curl --location --request POST 'https://api.getport.io/v1/auth/access_token' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "clientId": "'${{ secrets.PORT_CLIENT_ID }}'",
              "clientSecret": "'${{ secrets.PORT_CLIENT_SECRET }}'"
          }' | jq '.accessToken' | sed 's/"//g')
          echo "ACCESS_TOKEN=$access_token" >> $GITHUB_ENV

      - name: Sleep for 5 Seconds
        run: sleep 5

      - name: First Deployment - Step 1 with Logs (Success)
        id: step-1-deploy-1
        run: |
          curl -L -X POST "https://api.getport.io/v1/blueprints/step/entities" \
          -H "Authorization: Bearer ${{ env.ACCESS_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "identifier": "step-1-deployment-1-${{ github.run_id }}",
            "title": "Step 1 for First Deployment",
            "blueprint": "step",
            "properties": {
              "status": "COMPLETED",
              "status_message": "Step 1 completed successfully.",
              "log_stream": "### Log Stream for Step 1\n**Deployment:** deployment-2-${{ github.run_id }}\n**Status:** **COMPLETED**\n**Logs:**\n- [INFO] 2024-12-01T08:00:00Z: Initializing deployment for `payment-service`.\n- [INFO] 2024-12-01T08:00:10Z: Checking available resources on cluster `prod-cluster-02`.\n- [INFO] 2024-12-01T08:00:20Z: Resource check passed. CPU: 60% available, Memory: 70% available.\n- [INFO] 2024-12-01T08:00:30Z: Pulling container image `payment-service:v2.0.1` from registry `dockerhub.io`.\n- [INFO] 2024-12-01T08:00:50Z: Image pulled successfully.\n- [INFO] 2024-12-01T08:01:00Z: Applying Kubernetes deployment manifest.\n- [INFO] 2024-12-01T08:01:15Z: Deployment manifest validated and applied successfully.\n- [INFO] 2024-12-01T08:01:30Z: Waiting for Kubernetes pods to initialize...\n- [INFO] 2024-12-01T08:01:50Z: Pod `payment-service-abc123` in `Running` state. Readiness probe passed.\n- [INFO] 2024-12-01T08:02:00Z: Scaling deployment to 4 replicas.\n- [INFO] 2024-12-01T08:02:30Z: All replicas in `Running` state.\n- [INFO] 2024-12-01T08:02:45Z: Load balancer configuration successful.\n- [INFO] 2024-12-01T08:03:00Z: Verifying external access to service.\n- [INFO] 2024-12-01T08:03:20Z: Service accessible at `https://prod-cluster-02.example.com/payment-service`.\n- [SUCCESS] 2024-12-01T08:03:30Z: Deployment completed successfully."
            },
            "relations": {
              "deployment": "deployment-1-${{ github.run_id }}"
            }
          }'

      - name: Sleep for 5 Seconds
        run: sleep 5

      - name: First Deployment - Step 2 with Logs (Success)
        id: step-2-deploy-1
        run: |
          curl -L -X POST "https://api.getport.io/v1/blueprints/step/entities" \
          -H "Authorization: Bearer ${{ env.ACCESS_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "identifier": "step-2-deployment-1-${{ github.run_id }}",
            "title": "Step 2 for First Deployment",
            "blueprint": "step",
            "properties": {
              "status": "COMPLETED",
              "status_message": "Step 2 completed successfully.",
              "log_stream": "### Log Stream for Step 1\n**Deployment:** deployment-3-${{ github.run_id }}\n**Status:** **COMPLETED**\n**Logs:**\n- [INFO] 2024-12-02T14:00:00Z: Initializing deployment for `auth-service`.\n- [INFO] 2024-12-02T14:00:15Z: Checking available resources on cluster `prod-cluster-03`.\n- [INFO] 2024-12-02T14:00:25Z: Resource check passed. CPU: 45% available, Memory: 55% available.\n- [INFO] 2024-12-02T14:00:40Z: Pulling container image `auth-service:v1.3.0` from registry `dockerhub.io`.\n- [INFO] 2024-12-02T14:01:10Z: Image pulled successfully.\n- [INFO] 2024-12-02T14:01:25Z: Applying Kubernetes deployment manifest.\n- [INFO] 2024-12-02T14:01:40Z: Deployment manifest validated and applied successfully.\n- [INFO] 2024-12-02T14:02:00Z: Pod `auth-service-def456` in `Running` state. Readiness probe passed.\n- [INFO] 2024-12-02T14:02:20Z: Scaling deployment to 2 replicas.\n- [INFO] 2024-12-02T14:02:50Z: All replicas in `Running` state.\n- [INFO] 2024-12-02T14:03:00Z: Verifying external access to service.\n- [INFO] 2024-12-02T14:03:20Z: Service accessible at `https://prod-cluster-03.example.com/auth-service`.\n- [SUCCESS] 2024-12-02T14:03:30Z: Deployment completed successfully."
            },
            "relations": {
              "deployment": "deployment-1-${{ github.run_id }}"
            }
          }'

      - name: Sleep for 5 Seconds
        run: sleep 5

      - name: Update First Deployment as Completed
        id: update-deployment-1
        run: |
          curl -L -X PATCH "https://api.getport.io/v1/blueprints/deployment/entities/deployment-1-${{ github.run_id }}" \
          -H "Authorization: Bearer ${{ env.ACCESS_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "properties": {
              "status": "COMPLETED",
              "status_message": "Deployment completed successfully after all steps."
            }
          }'

      - name: Sleep for 5 Seconds
        run: sleep 5

      - name: Second Deployment - Step 3 with Logs (Failure)
        id: step-3-deploy-2
        run: |
          curl -L -X POST "https://api.getport.io/v1/blueprints/step/entities" \
          -H "Authorization: Bearer ${{ env.ACCESS_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "identifier": "step-3-deployment-2-${{ github.run_id }}",
            "title": "Step 3 for Second Deployment",
            "blueprint": "step",
            "properties": {
              "status": "FAILED",
              "status_message": "Step 3 encountered an unexpected error.",
              "log_stream": "### Log Stream for Step 1\n**Deployment:** deployment-4-${{ github.run_id }}\n**Status:** **FAILED**\n**Logs:**\n- [INFO] 2024-12-03T10:00:00Z: Initializing deployment for `analytics-service`.\n- [INFO] 2024-12-03T10:00:15Z: Checking available resources on cluster `prod-cluster-04`.\n- [INFO] 2024-12-03T10:00:25Z: Resource check passed. CPU: 40% available, Memory: 50% available.\n- [INFO] 2024-12-03T10:00:40Z: Pulling container image `analytics-service:v1.5.0` from registry `dockerhub.io`.\n- [INFO] 2024-12-03T10:01:10Z: Image pulled successfully.\n- [INFO] 2024-12-03T10:01:25Z: Applying Kubernetes deployment manifest.\n- [ERROR] 2024-12-03T10:01:45Z: Failed to apply deployment manifest. Error: `Insufficient permissions to update namespace 'analytics'`.\n- [INFO] 2024-12-03T10:02:00Z: Rolling back changes.\n- [INFO] 2024-12-03T10:02:20Z: Changes rolled back successfully.\n- [ERROR] 2024-12-03T10:02:30Z: Deployment failed. Contact cluster administrator to resolve permission issues."
            },
            "relations": {
              "deployment": "deployment-2-${{ github.run_id }}"
            }
          }'

      - name: Sleep for 5 Seconds
        run: sleep 5

      - name: Update Second Deployment as Failed
        id: update-deployment-2
        run: |
          curl -L -X PATCH "https://api.getport.io/v1/blueprints/deployment/entities/deployment-2-${{ github.run_id }}" \
          -H "Authorization: Bearer ${{ env.ACCESS_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "properties": {
              "status": "FAILED",
              "status_message": "Deployment failed at Step 3 with error: Network timeout while pulling image."
            }
          }'

      - name: Sleep for 5 Seconds
        run: sleep 5

      - name: Update Workflow as Failed
        id: update-workflow
        run: |
          curl -L -X PATCH "https://api.getport.io/v1/blueprints/workflow/entities/${{ fromJson(inputs.port_payload).workflow_id }}" \
          -H "Authorization: Bearer ${{ env.ACCESS_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "properties": {
              "status": "FAILED",
              "status_message": "Workflow failed at deployment-2, step-3 with error: Network timeout while pulling image."
            }
          }'
