name: SSA 2 - Workflow with Deployment and Steps

on:
  workflow_dispatch:
    inputs:
      port_payload:
        required: true
        description: "Port's payload with details about the workflow entity."
        type: string

jobs:
  create-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Access Token
        id: generate-token
        run: |
          access_token=$(curl --location --request POST 'https://api.getport.io/v1/auth/access_token' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "clientId": "'${{ secrets.PORT_CLIENT_ID }}'",
              "clientSecret": "'${{ secrets.PORT_CLIENT_SECRET }}'"
          }' | jq '.accessToken' | sed 's/"//g')
          echo "ACCESS_TOKEN=$access_token" >> $GITHUB_ENV

      - name: Sanitize Workflow Identifier
        id: sanitize-workflow-id
        run: |
          sanitized_workflow_id=$(echo "${{ github.event.inputs.port_payload.run_id }}" | sed 's/[^A-Za-z0-9@_.+:\/=-]//g')
          echo "SANITIZED_WORKFLOW_ID=$sanitized_workflow_id" >> $GITHUB_ENV

      - name: Trigger Deployment Pipeline
        run: |
          curl -L -X POST "https://api.getport.io/v1/blueprints/deployment/entities" \
          -H "Authorization: Bearer ${{ env.ACCESS_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "identifier": "deployment-${{ github.run_id }}",
            "title": "Deployment for Workflow - ${{ env.SANITIZED_WORKFLOW_ID }}",
            "blueprint": "deployment",
            "properties": {
              "status": "IN_PROGRESS"
            },
            "relations": {
              "workflow": "${{ env.SANITIZED_WORKFLOW_ID }}"
            }
          }'

  create-steps:
    needs: create-deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Access Token
        id: generate-token
        run: |
          access_token=$(curl --location --request POST 'https://api.getport.io/v1/auth/access_token' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "clientId": "'${{ secrets.PORT_CLIENT_ID }}'",
              "clientSecret": "'${{ secrets.PORT_CLIENT_SECRET }}'"
          }' | jq '.accessToken' | sed 's/"//g')
          echo "ACCESS_TOKEN=$access_token" >> $GITHUB_ENV

      - name: Create First Step
        id: create-step1
        run: |
          curl -L -X POST "https://api.getport.io/v1/blueprints/step/entities" \
          -H "Authorization: Bearer ${{ env.ACCESS_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "identifier": "step-1-${{ github.run_id }}",
            "title": "Step 1 for Deployment",
            "blueprint": "step",
            "properties": {
              "status": "COMPLETED"
            },
            "relations": {
              "deployment": "deployment-${{ github.run_id }}"
            }
          }'

      - name: Simulate Step 2 Failure
        id: create-step2
        run: |
          curl -L -X POST "https://api.getport.io/v1/blueprints/step/entities" \
          -H "Authorization: Bearer ${{ env.ACCESS_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "identifier": "step-2-${{ github.run_id }}",
            "title": "Step 2 for Deployment",
            "blueprint": "step",
            "properties": {
              "status": "FAILED"
            },
            "relations": {
              "deployment": "deployment-${{ github.run_id }}"
            }
          }'

      - name: Update Deployment as Failed
        if: always()
        run: |
          curl -L -X PATCH "https://api.getport.io/v1/blueprints/deployment/entities/deployment-${{ github.run_id }}" \
          -H "Authorization: Bearer ${{ env.ACCESS_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "properties": {
              "status": "FAILED"
            }
          }'

      - name: Update Workflow as Failed
        if: always()
        run: |
          curl -L -X PATCH "https://api.getport.io/v1/blueprints/workflow/entities/${{ env.SANITIZED_WORKFLOW_ID }}" \
          -H "Authorization: Bearer ${{ env.ACCESS_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "properties": {
              "status": "FAILED"
            }
          }'
