name: SSA 2 - Workflow with Detailed Steps and Logs

on:
  workflow_dispatch:
    inputs:
      port_payload:
        required: true
        description: "Port's payload with details about the workflow entity."
        type: string

jobs:
  create-deployments:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Access Token
        id: generate-token
        run: |
          access_token=$(curl --location --request POST 'https://api.getport.io/v1/auth/access_token' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "clientId": "'${{ secrets.PORT_CLIENT_ID }}'",
              "clientSecret": "'${{ secrets.PORT_CLIENT_SECRET }}'"
          }' | jq '.accessToken' | sed 's/"//g')
          echo "ACCESS_TOKEN=$access_token" >> $GITHUB_ENV

      - name: Sleep for 5 Seconds
        run: sleep 5

      - name: Trigger First Deployment
        id: deploy-1
        run: |
          curl -L -X POST "https://api.getport.io/v1/blueprints/deployment/entities" \
          -H "Authorization: Bearer ${{ env.ACCESS_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "identifier": "deployment-1-${{ github.run_id }}",
            "title": "First Deployment for Workflow - ${{ fromJson(inputs.port_payload).workflow_id }}",
            "blueprint": "deployment",
            "properties": {
              "status": "IN_PROGRESS",
              "status_message": "First deployment is in progress."
            },
            "relations": {
              "workflow": "${{ fromJson(inputs.port_payload).workflow_id }}"
            }
          }'

      - name: Sleep for 5 Seconds
        run: sleep 5

      - name: Trigger Second Deployment
        id: deploy-2
        run: |
          curl -L -X POST "https://api.getport.io/v1/blueprints/deployment/entities" \
          -H "Authorization: Bearer ${{ env.ACCESS_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "identifier": "deployment-2-${{ github.run_id }}",
            "title": "Second Deployment for Workflow - ${{ fromJson(inputs.port_payload).workflow_id }}",
            "blueprint": "deployment",
            "properties": {
              "status": "IN_PROGRESS",
              "status_message": "Second deployment is in progress."
            },
            "relations": {
              "workflow": "${{ fromJson(inputs.port_payload).workflow_id }}"
            }
          }'

  process-steps:
    needs: create-deployments
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Access Token
        id: generate-token
        run: |
          access_token=$(curl --location --request POST 'https://api.getport.io/v1/auth/access_token' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "clientId": "'${{ secrets.PORT_CLIENT_ID }}'",
              "clientSecret": "'${{ secrets.PORT_CLIENT_SECRET }}'"
          }' | jq '.accessToken' | sed 's/"//g')
          echo "ACCESS_TOKEN=$access_token" >> $GITHUB_ENV

      - name: Sleep for 5 Seconds
        run: sleep 5

      - name: First Deployment - Step 1 with Logs (Success)
        id: step-1-deploy-1
        run: |
          curl -L -X POST "https://api.getport.io/v1/blueprints/step/entities" \
          -H "Authorization: Bearer ${{ env.ACCESS_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "identifier": "step-1-deployment-1-${{ github.run_id }}",
            "title": "Step 1 for First Deployment",
            "blueprint": "step",
            "properties": {
              "status": "COMPLETED",
              "status_message": "Step 1 completed successfully.",
              "log_stream": "### Log Stream for Step 1\n**Deployment:** deployment-1-${{ github.run_id }}\n**Status:** **COMPLETED**\n\n**Logs:**\n- Starting deployment for `user-service`.\n- Verifying access to container registry at `registry.example.com`.\n- Pulling container image `user-service:v1.2.3`:\n  - Layer 1/3: Downloaded successfully.\n  - Layer 2/3: Downloaded successfully.\n  - Layer 3/3: Downloaded successfully.\n- Applying Kubernetes deployment manifest:\n  - Namespace: `production`.\n  - Resources: 2 CPU, 4GB RAM.\n  - Service: Exposed on port 443.\n- Deployment completed successfully:\n  - Service is available at `https://prod-cluster-01.example.com/user-service`.\n  - Deployment timestamp: $(date -u +\"%Y-%m-%dT%H:%M:%SZ\").\n"
            },
            "relations": {
              "deployment": "deployment-1-${{ github.run_id }}"
            }
          }'

      - name: Sleep for 5 Seconds
        run: sleep 5

      - name: First Deployment - Step 2 with Logs (Success)
        id: step-2-deploy-1
        run: |
          curl -L -X POST "https://api.getport.io/v1/blueprints/step/entities" \
          -H "Authorization: Bearer ${{ env.ACCESS_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "identifier": "step-2-deployment-1-${{ github.run_id }}",
            "title": "Step 2 for First Deployment",
            "blueprint": "step",
            "properties": {
              "status": "COMPLETED",
              "status_message": "Step 2 completed successfully.",
              "log_stream": "### Log Stream for Step 2\n**Deployment:** deployment-1-${{ github.run_id }}\n**Status:** **COMPLETED**\n\n**Logs:**\n- Running post-deployment validation:\n  - Health check endpoint: `https://prod-cluster-01.example.com/user-service/health`.\n  - Expected response: HTTP 200 OK.\n  - Actual response: HTTP 200 OK.\n- Validation passed successfully.\n- Deployment marked as stable.\n  - Service `user-service` is now live.\n  - Validation timestamp: $(date -u +\"%Y-%m-%dT%H:%M:%SZ\").\n"
            },
            "relations": {
              "deployment": "deployment-1-${{ github.run_id }}"
            }
          }'

      - name: Sleep for 5 Seconds
        run: sleep 5

      - name: Second Deployment - Step 3 with Logs (Failure)
        id: step-3-deploy-2
        run: |
          curl -L -X POST "https://api.getport.io/v1/blueprints/step/entities" \
          -H "Authorization: Bearer ${{ env.ACCESS_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "identifier": "step-3-deployment-2-${{ github.run_id }}",
            "title": "Step 3 for Second Deployment",
            "blueprint": "step",
            "properties": {
              "status": "FAILED",
              "status_message": "Step 3 encountered an unexpected error.",
              "log_stream": "### Log Stream for Step 3\n**Deployment:** deployment-2-${{ github.run_id }}\n**Status:** **FAILED**\n\n**Logs:**\n- Starting deployment for `order-service`.\n- Pulling container image `order-service:v2.5.1`:\n  - Error: Network timeout during layer 2/3 download.\n  - Retrying...\n  - Error: Registry unreachable after 3 retries.\n- Deployment aborted:\n  - Root cause: Network connectivity issue.\n  - Timestamp: $(date -u +\"%Y-%m-%dT%H:%M:%SZ\").\n"
            },
            "relations": {
              "deployment": "deployment-2-${{ github.run_id }}"
            }
          }'

      - name: Sleep for 5 Seconds
        run: sleep 5
