name: SSA 2 - Workflow with Multiple Deployments, Steps, and Logs

on:
  workflow_dispatch:
    inputs:
      port_payload:
        required: true
        description: "Port's payload with details about the workflow entity."
        type: string

jobs:
  create-deployments:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Access Token
        id: generate-token
        run: |
          access_token=$(curl --location --request POST 'https://api.getport.io/v1/auth/access_token' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "clientId": "'${{ secrets.PORT_CLIENT_ID }}'",
              "clientSecret": "'${{ secrets.PORT_CLIENT_SECRET }}'"
          }' | jq -r '.accessToken')
          echo "ACCESS_TOKEN=$access_token" >> $GITHUB_ENV

      - name: Create Deployment 1
        id: deploy-1
        run: |
          response=$(curl -s -L -X POST "https://api.getport.io/v1/blueprints/deployment/entities" \
          -H "Authorization: Bearer ${{ env.ACCESS_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "identifier": "deployment-1-${{ github.run_id }}",
            "title": "First Deployment for Workflow - ${{ fromJson(inputs.port_payload).workflow_id }}",
            "blueprint": "deployment",
            "properties": {
              "status": "IN_PROGRESS",
              "status_message": "Deployment 1 is in progress."
            },
            "relations": {
              "workflow": "${{ fromJson(inputs.port_payload).workflow_id }}"
            }
          }')

      - name: Run SSA to Create Steps for Deployment 1
        id: run-step-1
        run: |
          for i in {1..2}; do
            step_id="step-${i}-deployment-1-${{ github.run_id }}"
            response=$(curl -s -L -X POST "https://api.getport.io/v1/actions/step_log_stream/runs" \
            -H "Authorization: Bearer ${{ env.ACCESS_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "properties": {
                "step_identifier": "'${step_id}'",
                "step_title": "Step '${i}' for Deployment 1",
                "status": "IN_PROGRESS",
                "status_message": "IN_PROGRESS",
                "deployment": "deployment-1-${{ github.run_id }}"
              }
            }')
            run_id=$(echo "$response" | jq -r '.run.id')
            echo "STEP_ID_${i}=$step_id" >> $GITHUB_ENV
            echo "RUN_ID_STEP_${i}=$run_id" >> $GITHUB_ENV
            sleep 30
            curl -L -X PATCH "https://api.getport.io/v1/blueprints/step/entities/${step_id}?run_id=${run_id}" \
            -H "Authorization: Bearer ${{ env.ACCESS_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"properties\": {\"status\": \"COMPLETED\", \"log_stream\": \"https://app.getport.io/organization/run?runId=${run_id}\", \"status_message\": \"Step '${i}' completed successfully.\"}}"
            curl -L -X POST "https://api.getport.io/v1/actions/runs/${run_id}/logs" \
            -H "Authorization: Bearer ${{ env.ACCESS_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"terminationStatus\": \"SUCCESS\", \"statusLabel\": \"Completed\", \"message\": \"Step '${i}' for Deployment 1 completed successfully.\"}"
          done

      - name: Update Deployment 1 as Completed
        run: |
          curl -L -X PATCH "https://api.getport.io/v1/blueprints/deployment/entities/deployment-1-${{ github.run_id }}" \
          -H "Authorization: Bearer ${{ env.ACCESS_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "properties": {
              "status": "COMPLETED",
              "status_message": "Deployment 1 completed successfully."
            }
          }'

      - name: Fix Log Stream for Deployment 2 Step Failure
        run: |
          curl -L -X PATCH "https://api.getport.io/v1/blueprints/step/entities/${{ env.STEP_ID }}?run_id=${{ env.RUN_ID_STEP_2 }}" \
          -H "Authorization: Bearer ${{ env.ACCESS_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d "{\"properties\": {\"status\": \"FAILED\", \"log_stream\": \"https://app.getport.io/organization/run?runId=${{ env.RUN_ID_STEP_2 }}\", \"status_message\": \"Step failed due to an error.\"}}"

      - name: Update Deployment 2 as Failed
        run: |
          curl -L -X PATCH "https://api.getport.io/v1/blueprints/deployment/entities/deployment-2-${{ github.run_id }}" \
          -H "Authorization: Bearer ${{ env.ACCESS_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "properties": {
              "status": "FAILED",
              "status_message": "Deployment 2 failed due to step failure."
            }
          }'

      - name: Update Workflow as Failed
        run: |
          curl -L -X PATCH "https://api.getport.io/v1/blueprints/workflow/entities/${{ fromJson(inputs.port_payload).workflow_id }}" \
          -H "Authorization: Bearer ${{ env.ACCESS_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "properties": {
              "status": "FAILED",
              "status_message": "Workflow failed due to Deployment 2 failure."
            }
          }'
