name: SSA 2 - Workflow with Multiple Deployments, Steps, and Logs

on:
  workflow_dispatch:
    inputs:
      port_payload:
        required: true
        description: "Port's payload with details about the workflow entity."
        type: string

jobs:
  create-deployments:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Access Token
        id: generate-token
        run: |
          access_token=$(curl --location --request POST 'https://api.getport.io/v1/auth/access_token' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "clientId": "'${{ secrets.PORT_CLIENT_ID }}'",
              "clientSecret": "'${{ secrets.PORT_CLIENT_SECRET }}'"
          }' | jq -r '.accessToken')
          echo "ACCESS_TOKEN=$access_token" >> $GITHUB_ENV

      - name: Create Deployment 1
        id: deploy-1
        run: |
          response=$(curl -s -L -X POST "https://api.getport.io/v1/blueprints/deployment/entities" \
          -H "Authorization: Bearer ${{ env.ACCESS_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "identifier": "deployment-1-${{ github.run_id }}",
            "title": "First Deployment for Workflow - ${{ fromJson(inputs.port_payload).workflow_id }}",
            "blueprint": "deployment",
            "properties": {
              "status": "IN_PROGRESS",
              "status_message": "Deployment 1 is in progress."
            },
            "relations": {
              "workflow": "${{ fromJson(inputs.port_payload).workflow_id }}"
            }
          }')

      - name: Run SSA to Create Step for Deployment 1
        id: run-step-1
        run: |
          step_id="step-1-deployment-1-${{ github.run_id }}"
          response=$(curl -s -L -X POST "https://api.getport.io/v1/actions/step_log_stream/runs" \
          -H "Authorization: Bearer ${{ env.ACCESS_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "properties": {
              "step_identifier": "'${step_id}'",
              "step_title": "Step 1 for Deployment 1",
              "status": "IN_PROGRESS",
              "status_message": "IN_PROGRESS",
              "deployment": "deployment-1-${{ github.run_id }}"
            }
          }')
          run_id=$(echo "$response" | jq -r '.run.id')
          echo "STEP_ID=$step_id" >> $GITHUB_ENV
          echo "RUN_ID_STEP_1=$run_id" >> $GITHUB_ENV

      - name: Wait for 5 Seconds
        run: sleep 5

      - name: Update Step Entity with Run ID
        run: |
          curl -L -X PATCH "https://api.getport.io/v1/blueprints/step/entities/${{ env.STEP_ID }}?run_id=${{ env.RUN_ID_STEP_1 }}" \
          -H "Authorization: Bearer ${{ env.ACCESS_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{}'

      - name: Log Step Execution to SSA Run
        run: |
          curl -L -X POST "https://api.getport.io/v1/actions/runs/${{ env.RUN_ID_STEP_1 }}/logs" \
          -H "Authorization: Bearer ${{ env.ACCESS_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "terminationStatus": "SUCCESS",
            "statusLabel": "Completed",
            "message": "Step for Deployment 1 created successfully via SSA."
          }'

  update-workflow:
    needs: create-deployments
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Access Token
        id: generate-token
        run: |
          access_token=$(curl --location --request POST 'https://api.getport.io/v1/auth/access_token' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "clientId": "'${{ secrets.PORT_CLIENT_ID }}'",
              "clientSecret": "'${{ secrets.PORT_CLIENT_SECRET }}'"
          }' | jq -r '.accessToken')
          echo "ACCESS_TOKEN=$access_token" >> $GITHUB_ENV

      - name: Update Workflow as Completed
        id: update-workflow
        run: |
          curl -L -X PATCH "https://api.getport.io/v1/blueprints/workflow/entities/${{ fromJson(inputs.port_payload).workflow_id }}" \
          -H "Authorization: Bearer ${{ env.ACCESS_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "properties": {
              "status": "COMPLETED",
              "status_message": "Workflow completed successfully."
            }
          }'
